# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

before_script:
  - gem install awesome_bot

language: ruby

rvm:
  - 2.2

script:
  - ./scripts/check-links.sh
