# For more information about the configurations used
# in this file, please see the Travis CI documentation.
#
# https://docs.travis-ci.com

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

before_script:
  - gem install awesome_bot

dist: trusty

language: ruby

notifications:
  email:
    on_failure: always
    on_success: never

rvm:
  - 2.2

script:
  - ./scripts/check-links.sh
